# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='option',
            field=models.CharField(blank=True, choices=[('F', 'Farmer'), ('B', 'Buyer')], max_length=1),
        ),
    ]
